---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-player-router
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    revision: "{{ .Release.Revision }}"
    app.kubernetes.io/name: "{{ .Values.appName }}-player-router"
spec:
  selector:
    matchLabels:
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      app.kubernetes.io/name: "{{ .Values.appName }}-player-router"
  replicas: {{ $.Values.playerRouter.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      {{- if (eq (int $.Values.playerRouter.replicaCount) 1) }}
      maxUnavailable: 0
      {{- else }}
      maxUnavailable: 1
      {{- end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/name: "{{ .Values.appName }}-player-router"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    release: {{ .Release.Name }}
                    heritage: {{ .Release.Service }}
                    app.kubernetes.io/name: "{{ .Values.appName }}-player-router"
                topologyKey: kubernetes.io/hostname
            - weight: 50
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
                    release: {{ .Release.Name }}
                    heritage: {{ .Release.Service }}
                    app.kubernetes.io/name: "{{ .Values.appName }}-player-router"
                topologyKey: topology.kubernetes.io/zone
      terminationGracePeriodSeconds: 10
      serviceAccountName: default
      containers:
        - name: player-router
          image: {{ .Values.playerRouter.image }}
          imagePullPolicy: {{ $.Values.playerRouter.imagePullPolicy }}
          resources:
            requests:
              memory: {{ $.Values.playerRouter.resources.requests.memory }}
              cpu: {{ $.Values.playerRouter.resources.requests.cpu }}
            limits:
              memory: {{ $.Values.playerRouter.resources.limits.memory }}
              cpu: {{ $.Values.playerRouter.resources.limits.cpu }}
          env: []
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /alive
              port: http
              scheme: HTTP
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
            timeoutSeconds: 5